SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
LIVES = 3
INITIAL_SCORE = 0
ASTEROID_SPEED = 2
SHIP_THRUST = 0.1
SHIP_ROTATION_SPEED = 3
ROCKET_SPEED = 8
ROCKET_LIFETIME = 100
MIN_ASTEROIDS = 5
MAX_ASTEROIDS = 10

SPRITE_FOLDER = "public"
HEART_IMAGE_SIZE = 32
HEART_IMAGE_FILENAME = f"heart pixel art {HEART_IMAGE_SIZE}x{HEART_IMAGE_SIZE}.png"
STATIC_SHIP_SPRITE = "static_ship.png"
THRUSTING_SHIP_SPRITE = "thrusting_ship.png"
